name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're facing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered other approaches?
      placeholder: Describe alternative solutions you've considered
    validations:
      required: false

  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      description: Does this fit the MVP scope?
      options:
        - label: This is essential for MVP
        - label: This can wait until after MVP
        - label: I'm not sure about the scope
